Adminpage
WildCodeSchool/orleans-0917-karura pull request #11
Opened 2017-10-25 13:36 UTC by NoclainB

Page principale d'administration. Concernant les .htaccess et .htpasswd, je suis en attente d'un live coding la semaine prochaine. sur ce sujet.

2017-10-26 10:13 UTC, sblondeau requested changes

2017-10-26 10:13 UTC, sblondeau commented on src/View/Admin/adminMainPage.html.twig
> +                <a href="admin.php?route=adminformreceptionaddressupdate" class="thumbnail">
c'est un peu illisible non ? faire du camelCase ou admin-form-reception-adress-update à la rigueur
mais admin-adresse-update suffirait peut etre ?

2017-10-26 12:06 UTC, NoclainB commented on src/View/Admin/adminMainPage.html.twig
> +                <a href="admin.php?route=adminformreceptionaddressupdate" class="thumbnail">
C'est fait

2017-10-26 12:23 UTC, sblondeau requested changes

2017-10-26 12:23 UTC, sblondeau commented on src/View/Admin/headeradmin.html.twig
> +                    <li><a href="admin.php?route=adminformreceptionaddressupdate">Administration Email</a></li>
du coup il faut la changer ici aussi ta route non ?

2017-10-26 12:23 UTC, sblondeau commented on public/.htpasswd
> +carinnekarura:$apr1$WreIaJ4l$dJ9zfqX4Ole8kkBU/R5vT/
ok pour voir ça bientot mais dans tous les cas il ne faut pas que le fichier htpasswd soit versionné puisqu'il contient le mot de passe ;-)

2017-10-26 12:23 UTC, sblondeau commented on src/View/home.html.twig
> +                            <span>{{ category[0].name }}</span>
je ne comprends pas bien ce que tu veux faire ici? peux tu m'expliquer ?

2017-10-26 14:25 UTC, NoclainB commented on src/View/home.html.twig
> +                            <span>{{ category[0].name }}</span>
C'était un test pour modifier le nom de la categorie de façon dynamique.

2017-10-26 14:25 UTC, NoclainB commented on src/View/Admin/headeradmin.html.twig
> +                    <li><a href="admin.php?route=adminformreceptionaddressupdate">Administration Email</a></li>
done

2017-10-27 07:23 UTC, sblondeau approved these changes

2017-10-27 07:23 UTC, merged