Branche de bon gout avec des mises en formes partout et tout
WildCodeSchool/orleans-0917-karura pull request #14
Opened 2017-10-26 10:02 UTC by cuystasse

Merci pour la correction sensei !

2017-10-26 14:24 UTC, sblondeau requested changes
Je ne devrais pas avoir de PR juste pour du design :p c'est à régler dans chaque US, c'est pas une US indépendante... et en plus elle est un peu grosse la PR :p

2017-10-26 14:24 UTC, sblondeau commented on public/assets/css/style.css
> +    /*background-color: #E3E3E3;*/
pas de code commenté !

2017-10-26 14:24 UTC, sblondeau commented on src/View/home.html.twig
> +                                            <p class="text">{{ models[declinations[1].modelId] | capitalize }}</p>
pourquoi vous appelez des indices de declinations ? y a pas moyen de boucler plutot ?

2017-10-29 12:58 UTC, cuystasse commented on public/assets/css/style.css
> +    /*background-color: #E3E3E3;*/
done

2017-10-29 13:00 UTC, cuystasse commented on src/View/home.html.twig
> +                                            <p class="text">{{ models[declinations[1].modelId] | capitalize }}</p>
J'ai refactoré en faisant une boucle pour les indices 1 à 4 mais je préfère rester KISS putôt que de mettre des if sur l'indice 0 (qui a un comportement différent des autres indices) pour l'affichage (sachant qu'on utilise déjà l'indice de la boucle supérieur pour alternet les thumbnails).
Du coup Done.

2017-10-29 13:04 UTC, cuystasse commented
Bon pour merging

2017-10-30 12:45 UTC, sblondeau approved these changes
J'accepte mais PR trop grosse

2017-10-30 12:45 UTC, sblondeau commented on src/Controller/ModelController.php
> +            if ($declination->getColorId() == ($_GET["colorId"])) {
parenthèses en trop autour du GET mais c'est un détail

2017-10-30 12:48 UTC, merged