US : Main color for models
WildCodeSchool/orleans-0917-karura pull request #21
Opened 2017-11-02 16:09 UTC by cuystasse

Ajout de la fonctionnalité permettant la mise en avant d'une seule création par modèle + modif côté admin pour en changer

2017-11-03 09:20 UTC, sblondeau requested changes
tu mets toi meme dans le commit que tu as fais plusieurs chose (add et update), essaie de me faire 2 PR la prochaine fois !

2017-11-03 09:20 UTC, sblondeau commented on src/Model/DeclinationManager.php
> +    public function findByModel(Model $model, Bool $mainOnly=false )
bool avec un b minuscule

2017-11-03 10:23 UTC, cuystasse commented
Je vais essayer de segmenter d'avantage mon travail

2017-11-03 15:44 UTC, sblondeau requested changes

2017-11-03 15:44 UTC, sblondeau commented on src/Controller/DeclinationController.php
> +                var_dump($declinations);
attention au var_dump !!!! pas bien testé ;-)

2017-11-03 15:44 UTC, sblondeau commented on src/Controller/DeclinationController.php
> +                    var_dump($declinations);
et un autre ici

2017-11-03 15:44 UTC, sblondeau commented on src/Model/DeclinationManager.php
> +    public function findByCategory(Category $category, Bool $mainOnly=false)
encore un Bool en majuscule !

2017-11-03 15:44 UTC, sblondeau commented on src/View/Admin/adminDeclination.html.twig
>                          <figure>
pour moi la balise figure devrait etre au niveau de l'emploi de la classe thumbnail

2017-11-03 15:44 UTC, sblondeau commented on src/View/Admin/adminModels.html.twig
>                          <small class="pull-right">{{ models | length }} modèles</small>
et là tu ne gères pas le pluriel comme partout ailleurs ? :p

2017-11-03 15:44 UTC, sblondeau commented on src/View/Admin/adminModels.html.twig
> +                                        <strong> Il y a {{ declinationsNumber[model.id] }} créations associées à ce
pareil, le pluriel, si tu veux faire les choses bien, il faut le faire partout ;-)

2017-11-03 16:05 UTC, cuystasse commented on src/Controller/DeclinationController.php
> +                var_dump($declinations);
sorry j'ai enlevé le exit avant redirection mais pas les var_dump, je rêgle ça.

2017-11-06 10:05 UTC, sblondeau approved these changes

2017-11-06 10:05 UTC, sblondeau commented on src/Controller/ModelController.php
> +        $active_category = !empty($_GET['active_category']) ? $_GET['active_category'] : $categories[0]->getName() ;
pour le coup tu dois pouvoir faire un 
$active_category =  $_GET['active_category'] ?? $categories[0]->getName() ;

2017-11-06 10:05 UTC, sblondeau commented on src/Controller/ModelController.php
> +        $active_category = !empty($_GET['active_category']) ? $_GET['active_category'] : $categories[0]->getName() ;
et on y va mollo sur le ternaire ;-) ça peut vite devenir illisible

2017-11-06 10:05 UTC, merged