Demande généreuse de validation du sprint 2
WildCodeSchool/orleans-0917-karura pull request #3
Opened 2017-10-16 15:58 UTC by fsacado

PS : c'est Arnaud qui propse

2017-10-17 22:51 UTC, sblondeau requested changes
bien dans l'ensemble mais PR beaucoup trop grosse, très dur de bien tout relire donc j'ai sans doute laisser passer des choses que je vous redemanderai de corriger dans de futures PR ! essayer de plus découper vos PR par la suite

2017-10-17 22:51 UTC, sblondeau commented on public/index.php
> +($route == 'contact') {
pb de PSR, cette ligne devrait etre au dessus (et pareil plus bas)

2017-10-17 22:51 UTC, sblondeau commented on src/Controller/HomeController.php
> +            'data_id' => 'data',
c'est quoi ce 'data' que je vois partout ? je ne comprends pas ?

2017-10-17 22:51 UTC, sblondeau commented on src/Controller/ModelController.php
> +        $searchInformations = count($declinationsByModel) . ' résulats trouvés';
ça tu peux le faire coté vue avec un declinationByModel|length

2017-10-17 22:51 UTC, sblondeau commented on src/View/Admin/adminColor.html.twig
> +                <form action="deleteColor.php" method='post'>
attention à la route de ton action, pas bon là, tu dois passer par ton index.php

2017-10-17 22:51 UTC, sblondeau commented on src/View/base.html.twig
> +{% block body %}{% endblock %}
généralement on appelle se bloc "content" et non pas body car tu vois, il y a plein d'autres choses dans le body (mais c'est un détail, je présenterai le système de template bientot)

2017-10-17 22:51 UTC, sblondeau commented on src/View/home.html.twig
> +    <div class="container-fluid">
utiliser une balise section plutot qu'un div serait sans doute plus approprié ici

2017-10-17 22:51 UTC, sblondeau commented on src/View/Admin/adminColor.html.twig
> +{% block tbody %}
ça sort d'où ce "tbody" ?

2017-10-18 08:50 UTC, cuystasse commented
Les erreurs signalées ont été corrigées. Sauf les fichiers concernant l'administration des couleurs qui arriveront dans une feature prochaine (j'ai tiré une branche)

2017-10-20 10:16 UTC, closed without merging