Formulaire
WildCodeSchool/orleans-0917-karura pull request #7
Opened 2017-10-20 11:31 UTC by fsacado

2017-10-20 11:45 UTC, sblondeau requested changes

2017-10-20 11:45 UTC, sblondeau commented on src/Controller/Controller.php
> +    static public function getTwig(): \Twig_Environment
static ? pas besoin pour moi...

2017-10-20 11:45 UTC, sblondeau commented on src/Controller/Controller.php
> +    static public function setMessage2(string $type = 'info', string $title = 'Message : ', ...$message)
c'est quoi la diff entre setmessage et setmessage2 ? enommer avec des noms plus explicites

2017-10-20 11:45 UTC, sblondeau commented on src/Controller/HomeController.php
> +                $setTo = "loann.meignant@hotmail.fr";
pas de mail en dur

2017-10-20 11:45 UTC, sblondeau commented on src/Controller/HomeController.php
> +                    ->setTo([$setTo => 'Loann'])
pareil, pas d'infos en dur, dans le mail. Si c'est pour des tests, c'est que ce n'est pas terminé, donc ce n'est pas à mettre dans la PR. On n'envoie que des US terminnées !

2017-10-20 11:45 UTC, sblondeau commented on src/View/Admin/addColor.html.twig
> +            <form action="index.php?route=admincolor&action=add" method='post'>
du coup, c'est plus logique de faire une route=adminAddColor, vu qu'il y a un substr qui check si on est en "admin". Du coup, pas besoin du action

2017-10-20 11:45 UTC, sblondeau commented on src/View/Admin/adminMainPage.html.twig
> +    A faire :
mettre ça dans un //TODO pour ne pas le faire apparaitre sur la page html

2017-10-20 12:01 UTC, cuystasse commented on src/Controller/Controller.php
> +    static public function setMessage2(string $type = 'info', string $title = 'Message : ', ...$message)
Done, c'était juste un artefact de test.

2017-10-20 12:31 UTC, cuystasse commented on src/View/Admin/adminMainPage.html.twig
> +    A faire :
Done... euh non TODO en fait.

2017-10-20 12:43 UTC, cuystasse commented on src/View/Admin/addColor.html.twig
> +            <form action="index.php?route=admincolor&action=add" method='post'>
En cours de refactoring

2017-10-20 20:09 UTC, cuystasse commented on src/Controller/Controller.php
> +    static public function getTwig(): \Twig_Environment
Autant pour moi, je modifie ça.

2017-10-23 10:11 UTC, sblondeau requested changes

2017-10-23 10:11 UTC, sblondeau commented on mailConfig.php
> +$host = 'smtp.gmail.com';
il ne faut pas que le fichier contenant les mots de passe et identifiant soit versionné ! au meme titre que les identifiant BDD. Du coup tu peux créer des constantes supplémentaire dans le connect.php

2017-10-23 10:11 UTC, sblondeau commented on src/Controller/Controller.php
> +        if (self::$twig === Null) {
null en minuscule

2017-10-23 12:07 UTC, cuystasse commented on src/Controller/Controller.php
> +        if (self::$twig === Null) {
C'est parce qu'en python plutôt que le "null" on utilise le "None" qui possède un "N" majuscule.

2017-10-23 13:05 UTC, fsacado commented
Les deux remarques sont corrigées Sylvain.

2017-10-24 07:00 UTC, sblondeau approved these changes

2017-10-24 07:00 UTC, merged